### ISSUE TITLE
Problems when used with Yarn workspaces

### ISSUE THREAD

**Issue by k3n** [ember-cli/ember-cli-version-checker#47]
Background: [Workspaces in Yarn](https://yarnpkg.com/blog/2017/08/02/introducing-workspaces/)

In short, Yarn workspaces work by hoisting duplicate dependencies within a monorepo to the parent project, and things _just work_ because of the native `require()` process for finding dependencies (traversing up directories).

Problem: From what I can tell, `ember-cli-version-checker` manually finds dependencies, and doesn't follow the logic which powers `require()`, and so features such as dependency hoisting are a non-starter for Ember apps.

Are my assumptions correct thus far? If so, have there been any discussions around altering the logic to more closely resemble `require()`, or are there any viable known alternatives?

Thank you in advance, can provide more info as needed.

**Comment by rwjblue** [comment]
ember-cli-version-checker (since v2.0.0 at least) _only_ leverages the normal require algorithm to find npm dependencies.  v1.0.0 had the behavior you are describing.

Can you confirm which version you are using (note: there are often times multiple versions at play in an app...)?

Not too long ago @ef4 did a ton of work to go through and submit pull requests to all of the deps that were still using v1.0.0, I _believe_ they are all addressed and released at this point so you should try to update and make sure you are on latest of everything...

**Comment by k3n** [comment]
Hrmm, you're right. Still having issues in other places with dependencies, even after trying out ember-cli@2.18-beta. Going to shelve my work for now and let things settle. Thank you!
